kind = "web"
previewPath = "/"
title = "NAROS Esports"
version = "1.0.0"
id = "artifacts/naros-esports"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19958

[services.development]
run = "pnpm --filter @workspace/naros-esports run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/naros-esports", "run", "build" ]
publicDir = "artifacts/naros-esports/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19958"
BASE_PATH = "/"
